name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: pip install black pylint
        working-directory: backend/api

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          black_dir: backend/api
          pylint: true
          pylint_dir: backend/api
          continue_on_error: false
          auto_fix: false
