name: Lint

on: push

jobs:
  run-backend-linters:
    name: Run backend linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black pylint
        working-directory: backend

      - name: Run Pylint
        working-directory: backend
        run: pylint api
  
      - name: Run Black
        working-directory: backend
        run: black . --check
  

  run-frontend-linters:
    name: Run frontend linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
  
      - name: Install dependencies
        working-directory: frontend
        run: npm install
  
      - name: Run ESLint
        working-directory: frontend
        run: npm run lint
  
      - name: Run Prettier
        working-directory: frontend
        run: npm run prettier:check
  